name: Deploy Hugo site to Pages
on:
  push:
    branches: 
      - master
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-hugo@v3
        with:
          hugo-version: 'latest'
      - run: hugo --minify
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "./public"
      - id: deployment
        uses: actions/deploy-pages@v4
